### ISSUE TITLE
Retrieve Category with Transactions?

### ISSUE THREAD

**Issue by alexlaverty** [twang2218/node-cba-netbank#5]
Would it be possible to grab the Category along with the other transaction details?

```
Date, Transaction details, Category, Amount, Total
```
This would be very useful for stacked column graphs of expenses via Category.

**Comment by twang2218** [comment]
It would be great to classify the transactions into categories, however, I didn't find any efficient way to do it. Here is the transaction info returned from server:

#### Transaction Item

```yml
Date:
  Sort: [636338592000000000, '000000000000000000001']
  Text: 18 Jun 2017
MonthYear:
  Text: '062017'
WebSearch:
Description:
  Url: "/netbank/TransactionHistory/MerchantDetails.aspx?RID=_vozD1xI-EamV9q_EEbfLg&SID=KgNR8N%2fFPnc%3d&OD=WOOLWORTHS+CAL+W1993+++++KOGARAH&MId=5541&MN=5353109290853173&PDT=24%2f06%2f2017+12%3a00%3a00+AM&CT=MCD&TT=D"
  Sort: ["woolworths cal w1993     kogarah", -636333408000000000]
  Text: "WOOLWORTHS CAL W1993     KOGARAH"
SortableDebit:
  Sort: [1, 300]
  Text: "$300.00 DR"
SortableCredit:
  Sort: [0, 0]
  Text: ''
SortableAmount:
  Sort: [1, 300]
  Text: "$300.00 DR"
SortableCurrencyAmount:
  Sort: [2, 610.04]
  Text: "$610.04 CR"
Debit:
  Text: "$300.00 DR"
Credit:
  Text: ''
Amount:
  Text: "$300.00 DR"
Balance:
  Text: "$610.04 CR"
FeeLink:
  Text: ''
  Url:
  Type: ''
  FeeName: ''
TranCode:
  Text: '00 05'
ReceiptNumber:
  Text:
```

And only these information are useful:

* Dates: `Date.Sort[1]`: `YYYYMMDDHHmmssSSSSSSS`
* Description: `Description.Text`
* Amount: `Amount.Text`
* Balance: `Balance.Text`
* TranCode: `TranCode.Text`
* ReceiptNumber: `ReceiptNumber.Text`

`TranCode` is some kind of transaction type, rather than the merchant category. There is no category information in the transaction list data.

To get the the category/"Listed as" info, it has to send an individual request for each transaction, which is not efficient for hundreds or even thousands transactions.

Sometime, there are `MId` field in the `url`, such as: 

```
/netbank/TransactionHistory/MerchantDetails.aspx?RID=_vozD1xI-EamV9q_EEbfLg&SID=KgNR8N%2fFPnc%3d&OD=COLES+0762+++++++++++++++RAMSGATE++++AUS&MId=5411&PDT=24%2f06%2f2017+12%3a00%3a00+AM&CT=MCD&TT=D
```

Maybe it's possible to build a database of category for each `MId`, but this is still not cover all the cases.

Another possible solution is to build a database to map each merchant name, `Description`, to a category, and use the database and a classifier algorithm to find/guess the category, which could be an individual project.
